SELECT MAX(AR), MIN(AR) FROM kpu_rzhf WHERE AR IS NOT null;
SELECT AR FROM KPU_RZHF WHERE AR LIKE '%99';
SELECT count(ar) FROM kpu_rzhf WHERE ar IS not NULL;


SELECT sum(kfh_shu) FROM zem;
UPDATE zhiv
	SET OVCY_VSEGO = COALESCE(OVCEMATKI, 0) + COALESCE(barany, 0);

SELECT pashnya, posev FROM zem WHERE pashnya < posev;
SELECT vsego, kfh_shu, postroyki, vsego - ZEM_OTHER - POSTROYKI - KFH_SHU FROM zem WHERE vsego - POSTROYKI - POSTROYKI - KFH_SHU > 0;

UPDATE ZEM
	SET zem_other = ZEM_OTHER + 12
	WHERE ZEM_OTHER = 

UPDATE ZEM
	SET kfh_shu = kfh_shu - 12,
		ZEM_OTHER = coalesce(ZEM_OTHER, 0) + 12,
		pashnya = pashnya - 12
	WHERE kfh_shu > 12 AND pashnya > posev + 12;



SELECT MNOGOLETNIE, YABLOKI, YAGODY_PROCH FROM zem WHERE MNOGOLETNIE = COALESCE(YABLOKI, 0) + COALESCE(YAGODY_PROCH, 0) AND YAGODY_PROCH > 0;
UPDATE zem SET YABLOKI = YABLOKI + 100 WHERE YABLOKI IS NOT NULL ROWS 1;
SELECT sum(yabloki) FROM zem;
UPDATE zem SET mnogoletnie = COALESCE(YABLOKI, 0) + COALESCE(YAGODY_PROCH, 0) WHERE MNOGOLETNIE != COALESCE(YABLOKI, 0) + COALESCE(YAGODY_PROCH, 0);

SELECT posev FROM zem WHERE posev < COALESCE(semena_pods, 0) + COALESCE(ovoshi, 0) + COALESCE(soloma, 0);

SELECT * FROM zem WHERE id_catal = 24134;

UPDATE zem SET semena_masl = semena_pods;

SELECT sum(BAKLAZHAN) FROM zem;
SELECT count(baklazhan) FROM zem WHERE BAKLAZHAN > 10;

UPDATE zem
	SET ovoshi = COALESCE(kapusta, 0) + COALESCE(pertsy, 0) + COALESCE(OGURCY, 0) + COALESCE(BAKLAZHAN, 0) + COALESCE(POMIDOR, 0) + COALESCE(MORKOV, 0) + COALESCE(luk, 0) + COALESCE(KARTOFEL, 0);

UPDATE zem
	SET posev = COALESCE(SEMENA_MASL, 0) + COALESCE(ovoshi, 0) + COALESCE(SOLOMA, 0);
	
UPDATE zem
	SET BAKLAZHAN = null
	WHERE BAKLAZHAN = 10
	ROWS 102;